In [1]:
#problem_1
import numpy as np
import pandas as pd

def input_output(path):
    mnist_data = pd.read_csv(path) #reads the CSV file into a Pandas DataFrame
    x = np.array(mnist_data.iloc[:, 1:]) #this extracts the input features (flattened pixel values) from the DataFrame and convert to a NumPy array
    y = np.array(mnist_data.iloc[:, 0]) #this extracts the output labels from the DataFrame and convert to a NumPy array
    return x, y

path = "C:/Users/Administrator/Downloads/mnist_train.csv"
x, y = input_output(path) #(calls the input_output function to load the data and store the results in x and y)
print(x, y)
print(len(y))


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [5 0 4 ... 5 6 8]
60000


In [15]:
#problem2
import numpy as np
import pandas as pd
import os

path = "C:/Users/Administrator/Downloads/mnist_train.csv"
def get_input_output(path):
    
    #Reads MNIST data from the CSV file at the given path and return input and output arrays.
    
    mnist_data = pd.read_csv(path)
    input_arr = np.array(mnist_data.iloc[:, 1:])
    output_arr = np.array(mnist_data.iloc[:, 0])
    return input_arr, output_arr

input_arr, output_arr = get_input_output(path)

#Initializes the weights and biases with random values
parameters = np.random.normal(0, 0.001, size=(784, 10))
bias = np.random.normal(0, 0.1, size=(1, 10))

#Chooses a random sample index for training
sample_index = np.random.randint(len(output_arr))

#Sets the learning rate
learning_rate = 0.01

def softmax(x):
    
    #Computes the softmax of the given array x.
    
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

def loss_function(input_arr, output_arr, sample_index):
    
    #Computes the loss and the one-hot encoded target array for the given sample index.
    
    target_arr = np.zeros(10)
    target_arr[output_arr[sample_index]] = 1
    output_arr_softmax = softmax(np.dot(input_arr[sample_index], parameters) + bias)
    loss = -np.sum(target_arr * np.log(output_arr_softmax))
    return loss, target_arr

def backward_pass(input_arr, output_arr, parameters, bias, learning_rate):
    
    #Performs one epoch of backward pass for the given input, output, parameters, bias, and learning rate.
    
    loss, target_arr = loss_function(input_arr, output_arr, sample_index)
    input_sample = np.array(input_arr[sample_index])
    input_sample = input_sample.reshape(1, 784)
    error = softmax(np.dot(input_sample, parameters) + bias) - target_arr
    grad_parameters = np.dot(input_sample.T, error)
    grad_bias = np.sum(error, axis=0)
    parameters = parameters - learning_rate * grad_parameters
    bias = bias - learning_rate * grad_bias
    return parameters, bias

parameters, bias = backward_pass(input_arr, output_arr, parameters, bias, learning_rate)
print(backward_pass(input_arr, output_arr, parameters, bias, learning_rate))


(array([[-9.31941170e-06, -1.14157910e-03, -3.39108364e-04, ...,
        -3.98147450e-04,  8.95732683e-04, -3.35971724e-05],
       [-8.50007215e-04, -2.01036818e-04, -1.13660334e-03, ...,
        -3.64616655e-04,  6.48214337e-04,  1.35186318e-03],
       [ 1.18454866e-03, -1.39720492e-03,  9.21718113e-04, ...,
        -8.76726851e-04, -1.37563915e-03,  2.03709033e-04],
       ...,
       [ 1.61960482e-03, -1.99913057e-03, -5.21432778e-04, ...,
         3.81783465e-04, -3.68460505e-04, -2.37986776e-03],
       [-1.04754825e-03, -1.27426119e-03,  6.98742792e-04, ...,
         5.22584477e-04, -6.15948012e-04, -1.00201660e-03],
       [ 1.18162535e-03, -1.56673795e-03,  9.95234515e-04, ...,
         1.64490539e-03,  5.72092489e-04, -8.40792168e-04]]), array([[-0.1549276 ,  0.04038649, -0.01971529,         nan,  0.06694645,
        -0.06071769,  0.01614804,  0.06314094,  0.12269776, -0.1075308 ]]))


C:\Users\Administrator\AppData\Local\Temp\ipykernel_9140\4043535931.py:31: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9140\4043535931.py:32: RuntimeWarning: invalid value encountered in divide
  return exp_x / np.sum(exp_x)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9140\4043535931.py:41: RuntimeWarning: divide by zero encountered in log
  loss = -np.sum(target_arr * np.log(output_arr_softmax))
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9140\4043535931.py:41: RuntimeWarning: invalid value encountered in multiply
  loss = -np.sum(target_arr * np.log(output_arr_softmax))


In [56]:
#problem3
import numpy as np
import pandas as pd


path = "C:/Users/Administrator/Downloads/mnist_train.csv"
def input_output(path):
    mnist_data = pd.read_csv(path) # default header value is zero, therefore the first row is treated as header and the second row in data table has index 0
    x = np.array(mnist_data.iloc[:, 1:]) # this gives us the 60000 flattened pixels(784) values
    y = np.array(mnist_data.iloc[:, 0]) # this gives us 60000 labels 
    return x,y

a, b = input_output(path)
n = 10 # number of nodes in the hidden layer
X = np.array(a[0])
parameters_0 = np.random.normal(0, 0.001, size=(784, n)) # weights connecting the input and hidden layer
parameters_1 = np.random.normal(0, 0.001, size=(n, 10)) # weights connecting the hidden and output layer
parameters = [parameters_0, parameters_1]

bias_0 = np.random.normal(0, 0.1, size=(1, n)) # bias term connected to each node of hidden layer
bias_1 = np.random.normal(0, 0.1, size=(1, 10)) # bias term connected to each node of output layer
bias = [bias_0, bias_1]

i = np.random.randint(len(b)) # randomly select an index from the data
learning_rate = 0.01

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def softmax(z):
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z)

def forward_pass(X, parameters, bias):
    z_0 = np.dot(X, parameters[0]) + bias[0]
    y_0 = sigmoid(z_0)
    z_1 = np.dot(y_0, parameters[1]) + bias[1]
    y_1 = softmax(z_1)
    return y_0, y_1

def loss_function(y_pred, y_true):
    # convert y_true into one-hot encoding
    Y = np.zeros(10)
    Y[y_true] = 1
    # calculate cross-entropy loss
    loss = -np.sum(Y * np.log(y_pred))
    return loss

def backward_pass(X, Y, y_pred, parameters, bias, learning_rate):
    # calculate errors and gradients for output layer
    error_1 = y_pred - Y
    gradient_parameters_1 = np.dot(y_0.T, error_1)
    gradient_bias_1 = np.sum(error_1, axis=0)
    # calculate errors and gradients for hidden layer
    error_0 = np.dot(error_1, parameters[1].T) * y_0 * (1 - y_0)
    gradient_parameters_0 = np.dot(X.reshape(1, -1).T, error_0)
    gradient_bias_0 = np.sum(error_0, axis=0)
    # update parameters and bias terms
    parameters[0] -= learning_rate * gradient_parameters_0
    bias[0] -= learning_rate * gradient_bias_0
    parameters[1] -= learning_rate * gradient_parameters_1
    bias[1] -= learning_rate * gradient_bias_1
    return parameters, bias

# run one epoch of training
for j in range(len(b)):
    X = np.array(a[j])
    Y = b[j]
    y_0, y_1 = forward_pass(X, parameters, bias)
    parameters, bias = backward_pass(X, Y, y_1, parameters, bias, learning_rate)

# Initialize random weights and bias
weights = np.random.randn(784, 10)
bias = np.random.randn(1, 10)

# Initialize input vector
x = np.random.randn(784, 1)

# Calculate output of neural network
z = np.dot(weights.T, x) + bias.T
a = sigmoid(z)

# Print the numerical values of the arrays
print(weights)
print(bias)
print(x)
print(z)
print(a)

print("Predicted:", np.argmax(y_1), "Actual:", Y)



c:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9140\2648826350.py:31: RuntimeWarning: overflow encountered in exp
  exp_z = np.exp(z)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9140\2648826350.py:32: RuntimeWarning: invalid value encountered in divide
  return exp_z / np.sum(exp_z)


[[-7.93978176e-01  1.82249967e+00 -1.32133530e-01 -8.31946052e-01
  -3.60475216e-01 -4.29599331e-01  5.10412639e-01 -3.60349290e-01
   9.96430068e-01  9.89190464e-01]
 [ 7.62223285e-01  1.30155961e+00 -6.90561454e-01 -7.61623461e-01
   1.57699496e-01 -5.41437035e-01 -1.26773571e+00  1.75819997e+00
  -1.48397835e+00  2.65623271e-01]
 [ 6.79500411e-01  6.10084351e-02 -4.35488536e-01  2.77377414e-01
  -1.35848050e-01 -1.34844022e+00  1.50818167e+00  1.30567577e+00
   4.36501122e-01  6.15081417e-01]
 [-3.97021773e-02 -5.63773471e-01  1.80073077e+00  6.89164166e-01
   1.05450139e+00 -4.46303582e-01  1.48613048e+00  6.61064719e-01
  -1.33024908e+00 -1.16968617e+00]
 [ 1.96167259e+00  1.37841489e+00  8.83907891e-01 -2.48311177e-01
  -4.51427980e-01 -2.67985732e-01 -4.58437184e-01 -7.72695863e-01
   1.69400592e-01  1.75916591e+00]
 [ 1.35690235e+00  2.20210952e+00 -2.38619491e+00 -7.11701342e-01
   2.97141982e+00  7.24820337e-01  4.14090922e-01  7.37536764e-02
   1.39898261e+00  1.04818909e+00

In [53]:
#problem4
import numpy as np
import pandas as pd

def input_output(path):
    mnist_data = pd.read_csv(path)
    x = np.array(mnist_data.iloc[:, 1:])
    y = np.array(mnist_data.iloc[:, 0])
    return x, y

path = "C:/Users/Administrator/Downloads/mnist_train.csv"
X, Y = input_output(path)

def initialize_parameters(number_of_nodes, n):
    np.random.seed(1)
    parameters = []
    bias = []
    for i in range(n + 1):
        if i == 0:
            parameters.append(np.random.normal(0, 0.001, size=(784, number_of_nodes[i])))
        elif 1 <= i <= (n - 1):
            parameters.append(np.random.normal(0, 0.001, size=(number_of_nodes[i - 1], number_of_nodes[i])))
        else:
            parameters.append(np.random.normal(0, 0.001, size=(number_of_nodes[i - 1], 10)))

    for i in range(n + 1):
        if 0 <= i <= (n - 1):
            bias.append(np.random.normal(0, 0.001, size=(1, number_of_nodes[i])))
        else:
            bias.append(np.random.normal(0, 0.001, size=(1, 10)))

    return parameters, bias

number_of_nodes = [10, 10, 10, 10]
n = 4
parameters, bias = initialize_parameters(number_of_nodes, n)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def softmax(z):
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z)

def forward_pass(input, parameters, bias):
    Sigma = [input]
    Z = []
    for i in range(n + 1):
        z = np.dot(Sigma[-1], parameters[i]) + bias[i]
        Z.append(z)
        if 0 <= i <= (n - 1):
            sigma = sigmoid(z)
        else:
            sigma = softmax(z)
        Sigma.append(sigma)
    return Sigma

def loss_function(X, Y, j, parameters, bias):
    binary_output = np.zeros(10)
    binary_output[Y[j]] = 1
    p_o = forward_pass(X[j], parameters, bias)
    probability_output = p_o[-1]

    loss = -np.sum(binary_output * np.log(probability_output))
    return loss, binary_output

def backward_pass(input, binary_output, Sigma, parameters):
    gradients = []
    n = len(parameters) - 1
    error = (binary_output - Sigma[-1]) * (Sigma[-1] * (1 - Sigma[-1]))
    gradients.append(np.dot(error.reshape(1, -1), Sigma[n-1].T))
    for i in range(n, 0, -1):
        error = np.dot(error, parameters[i].T) * (Sigma[i-1].reshape(10, 1) * (1 - Sigma[i-1].reshape(10, 1)))
        gradients.append(np.dot(error.reshape(1, -1), Sigma[i-1].reshape(1, -1).T))
    gradients.reverse()
    return gradients

def update_parameters(parameters, bias, gradients, learning_rate):
    for i in range(n + 1):
        parameters[i] -= learning_rate * gradients[i]
        bias[i] -= learning


In [52]:
#just alternate way of trying problem4 (personal trial) 
import numpy as np
import pandas as pd

def input_output(path):
    mnist_data = pd.read_csv(path)
    x = np.array(mnist_data.iloc[:, 1:])
    y = np.array(mnist_data.iloc[:, 0])
    return x, y

path = "C:/Users/Administrator/Downloads/mnist_train.csv"
X, Y = input_output(path)

def initialize_parameters(number_of_nodes, n):
    np.random.seed(1)
    parameters = []
    bias = []
    for i in range(n + 1):
        if i == 0:
            parameters.append(np.random.normal(0, 0.001, size=(784, number_of_nodes[i])))
        elif 1 <= i <= (n - 1):
            parameters.append(np.random.normal(0, 0.001, size=(number_of_nodes[i - 1], number_of_nodes[i])))
        else:
            parameters.append(np.random.normal(0, 0.001, size=(number_of_nodes[i - 1], 10)))

    for i in range(n + 1):
        if 0 <= i <= (n - 1):
            bias.append(np.random.normal(0, 0.001, size=(1, number_of_nodes[i])))
        else:
            bias.append(np.random.normal(0, 0.001, size=(1, 10)))

    return parameters, bias

number_of_nodes = [10, 10, 10, 10]
n = 4
parameters, bias = initialize_parameters(number_of_nodes, n)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def softmax(z):
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z)

def forward_pass(input, parameters, bias):
    Sigma = [input]
    Z = []
    for i in range(n + 1):
        z = np.dot(Sigma[-1], parameters[i]) + bias[i]
        Z.append(z)
        if 0 <= i <= (n - 1):
            sigma = sigmoid(z)
        else:
            sigma = softmax(z)
        Sigma.append(sigma)
    return Sigma

def loss_function(X, Y, j, parameters, bias):
    binary_output = np.zeros(10)
    binary_output[Y[j]] = 1
    p_o = forward_pass(X[j], parameters, bias)
    probability_output = p_o[-1]

    loss = -np.sum(binary_output * np.log(probability_output))
    return loss, binary_output

def backward_pass(input, binary_output, Sigma, parameters):
    gradients = []
    n = len(parameters) - 1
    error = (binary_output - Sigma[-1]) * (Sigma[-1] * (1 - Sigma[-1]))
    gradients.append(np.dot(error.reshape(1, -1), Sigma[n-1].T))
    for i in range(n, 0, -1):
        error = np.dot(error, parameters[i].T) * (Sigma[i-1].reshape(10, 1) * (1 - Sigma[i-1].reshape(10, 1)))
        gradients.append(np.dot(error.reshape(1, -1), Sigma[i-1].reshape(1, -1).T))
    gradients.reverse()
    return gradients

learning_rate = 0.1

for j in range(10):  # for each data point
    Sigma = forward_pass(X[j], parameters, bias)


In [ ]:
#problem5
import numpy as np
import pandas as pd


path = "C:/Users/Administrator/Downloads/mnist_train.csv"


def input_output(path):
    mnist_data = pd.read_csv(path)
    x = np.array(mnist_data.iloc[:, 1:])
    y = np.array(mnist_data.iloc[:, 0])
    return x, y


X, Y = input_output(path)

parameters = []
bias = []
number_of_nodes = [10, 10, 10, 10]
n = 4
j = np.random.randint(len(Y))

input = np.array(X[j])

# assigning initial parameters
for i in range(n + 1):
    if i == 0:
        parameters.append(np.random.normal(0, 0.001, size=(784, number_of_nodes[i])))
    elif 1 <= i <= (n - 1):
        parameters.append(np.random.normal(0, 0.001, size=(number_of_nodes[i - 1], number_of_nodes[i])))
    else:
        parameters.append(np.random.normal(0, 0.001, size=(number_of_nodes[i - 1], 10)))

# assigning initial biases
for i in range(n + 1):
    if 0 <= i <= (n - 1):
        bias.append(np.random.normal(0, 0.001, size=(1, number_of_nodes[i])))
    else:
        bias.append(np.random.normal(0, 0.001, size=(1, 10)))


# different gradient term is different for different activation functions
def activation_function(z):
    return np.maximum(z, 0)


def activation_function_gradient(z):
    return (z > 0).astype(int)


def softmax(z):
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z)


def forward_pass(input, parameters, bias):
    Sigma = [input]
    Z = []
    for i in range(n + 1):
        z = np.dot(Sigma[-1], parameters[i]) + bias[i]
        Z.append(z)
        if 0 <= i <= (n - 1):
            sigma = activation_function(z)
        else:
            sigma = softmax(z)
        Sigma.append(sigma)
    return Sigma, Z


Sigma, Z = forward_pass(input, parameters, bias)

learning_rate = 0.01


def loss_function(X, Y, j):
    binary_output = np.zeros(10)
    binary_output[Y[j]] = 1
    p_o = forward_pass(input, parameters, bias)
    probability_output = p_o[-1]

    loss = -np.sum(binary_output * np.log(probability_output))
    return loss, binary_output


loss, binary_output = loss_function(X, Y, j)

def backward_pass(input, binary_output, Sigma, Z, parameters, different_gradient_term):
    n = len(parameters)
    gradients = []
    error = binary_output - Z[-1]

    for i in range(n, 0, -1):
        # Reshape error array to match Sigma array
        error = np.dot(error, parameters[i].T) * different_gradient_term(Z[i - 1])
        error = error.reshape(-1, Sigma[i-1].shape[1], error.shape[-1])

        # Perform dot product between Sigma and error arrays
        gradient = np.dot(Sigma[i - 1].T, error)
        gradients.append(gradient)

    gradients.reverse()
    return gradients



gradients = backward_pass(input, binary_output, Sigma, Z, parameters, activation_function_gradient)

def update(parameters, bias, gradients, learning_rate):
    for i in range(n + 1):
        parameters[i] -= learning_rate * gradients[i]
        bias[i] -= learning_rate * np.mean
